### ISSUE TITLE
Needs a config file

### ISSUE THREAD

**Issue by frillip** [frillip/noip-rfc2136#5]
Editing variables in the main script is a terrible way of configuring things.

Proposed YAML config:
```
noip-rfc2136:
  dns:
    nameserver: 198.51.100.2
    zone: example.com.
    ttl: 30
    tsig_key_name: example_key_name
    tsig_key_secret: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1vSGc1U0pZUkhBMA==
    tsig_key_algorithm: hmac-sha256

  listen:
    host: 127.0.0.1
    port: 8000

  https:
    enabled: False
    key_file: /etc/letsencrypt/live/example.com/privkey.pem
    cert_file: /etc/letsencrypt/live/example.com/fullchain.pem

  auth:
    enabled: False
    user: user
    pass: pass

  log:
    level: INFO
```

@marrold whilst I'm meddling with `build_conf()`, I will update the environment variable names to be uppercase and prefixed with `NOIP_RFC2136_`, so the name server variable will end up being `NOIP_RFC2136_DNS_NAMESERVER`, unless you have any objections?
